name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: List Files
      shell: bash
      run: |
        ls ./Distributable -R
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: WoodenStatuettes
        path: ./Distributable/*
        if-no-files-found: error
